apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  template:
    spec:
      containers:
        - name: spring-backend
          image: synklabshareacc/ctrlline-staging:64dbb1
