apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    color: green
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
        labels:
          app: backend
          color: green
    spec:
      containers:
        - name: backend
          image: synklabshareacc/ctrlline-staging:64dbb1
