apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrlline-api-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctrlline-api
  template:
    metadata:
      labels:
        app: ctrlline-api
    spec:
      containers:
      - name: ctrlline-api
        image: synklabshareacc/ctrlline-staging:d16bc3
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ports:
        - containerPort: 8088
        envFrom:
          - configMapRef:
              name: ctrlline-config
          - configMapRef:
              name: global-config
          - secretRef:
              name: ctrlline-secret
        volumeMounts:
          - name: serial-storage
            mountPath: /var/ctrlline/serials
      volumes:
      - name: serial-storage
        persistentVolumeClaim:
          claimName: ctrlline-serial-pvc
        # startupProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8088
        #   failureThreshold: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8088
        #   initialDelaySeconds: 10
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8088
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
