apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    color: blue
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
        labels:
          app: backend
          color: blue
    spec:
      containers:
        - name: backend
          image: 980921712223.dkr.ecr.ap-northeast-2.amazonaws.com/ctrlline-backend:main-latest
