apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
spec:
  template:
    spec:
      containers:
        - name: backend
          image: 980921712223.dkr.ecr.ap-northeast-2.amazonaws.com/ctrlline-backend:main-latest
